#!/usr/bin/env bash

set -e

DEFAULT_CONFIG_PREFIX=("default" "packages")
DOTBOT_DIR="dotbot"
DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_DIR="${BASEDIR}/dotbot-plugins"
CONFIG_SUFFIX=".conf.yaml"

cd "${BASEDIR}"
git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
echo "Found ${DEFAULT_CONFIG_PREFIX}"
PLUGIN_ARGS=(
    --plugin-dir "${PLUGIN_DIR}/dotbot-apt"
    --plugin-dir "${PLUGIN_DIR}/dotbot-git"
    --plugin-dir "${PLUGIN_DIR}/dotbot-sudo"
)
if [[ "$OSTYPE" == "darwin"* ]]; then
    PLUGIN_ARGS+=(--plugin-dir "${PLUGIN_DIR}/dotbot-brew")
fi

for conf in ${DEFAULT_CONFIG_PREFIX} ${@}; do
    echo "Executing ${conf}${CONFIG_SUFFIX}"
    "${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" \
        "${PLUGIN_ARGS[@]}" \
        -c "${conf}${CONFIG_SUFFIX}"
done
#if [[ "$OSTYPE" == "linux-gnu" ]]; then
#	"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "${PLUGIN_DIR}/dotbot-git" --plugin-dir "{$PLUGIN_DIR}/apt-get" -c "${CONFIG}" "${@}"
#elif [[ "$OSTYPE" == "darwin"* ]]; then
#  	"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" --plugin-dir "${PLUGIN_DIR}/dotbot-brew" --plugin-dir "${PLUGIN_DIR}/dotbot-git" -c "${CONFIG}" "${@}"
#
#echo ok
#fi


