# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
neofetch
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
INC_APPEND_HISTORY=true
setopt autocd extendedglob
setopt -o sharehistory
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/gaz/.zshrc'
zstyle ':completion:*' list-colors ''

# End of lines added by compinstall
POWERLEVEL9K_MODE='nerdfont-complete'
#Load Zplugin
source ~/.zinit/zinit.zsh
source ~/.dotfiles/zsh/aliases.zsh

EDITOR=vim

#Log Zplugin Plugins
zinit load zsh-users/zsh-autosuggestions
zinit light zdharma-continuum/fast-syntax-highlighting
zinit ice depth=1; zinit light romkatv/powerlevel10k 
zinit snippet OMZP::common-aliases
zinit snippet OMZP::sudo
zinit snippet OMZP::fasd
zinit snippet OMZP::colored-man-pages

# Fix home/end on mac in zsh
bindkey "^[[H" beginning-of-line
bindkey "^[[F" end-of-line
# Make Option+Arrows and Option+Delete work like Linux shells

# Option + Left: backward-word
bindkey ";3D" backward-word
bindkey "^[b" backward-word  # ESC-b fallback

# Option + Right: forward-word
bindkey ";3C" forward-word
bindkey "^[f" forward-word   # ESC-f fallback

# Option + Delete: delete-word backwards
bindkey "^[^?" backward-kill-word

# Option + Fn + Delete (sometimes sends ^[[3;3~): delete-word forward
bindkey "^[[3;3~" kill-word

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

zinit ice atclone"dircolors -b LS_COLORS > clrs.zsh" \
    atpull'%atclone' pick"clrs.zsh" nocompile'!' \
    atload'zstyle ":completion:*" list-colors “${(s.:.)LS_COLORS}”'
zinit light trapd00r/LS_COLORS

autoload -Uz compinit
compinit
zstyle ':completion:*' menu select
zinit cdreplay -q

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# Setup pyenv if it exists
export PYENV_ROOT="$HOME/.pyenv"
if command -v "$PYENV_ROOT/bin/pyenv" 2>&1; then
  if command -v pyenv >/dev/null 2>&1 || export PATH="$PYENV_ROOT/bin:$PATH"; then
    eval "$(pyenv init -)"
  fi
fi
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
# Created by `pipx` on 2025-04-01 06:12:56
export PATH="$PATH:/Users/gaz/.local/bin"

# Created by `pipx` on 2025-07-02 04:59:19
export PATH="$PATH:/Users/gaz/Library/Python/3.9/bin"
